config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users,
              path:'',
              path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'},
              controllers: { registrations: 'users/registrations'}

  root 'chatroom#index'

  post 'message', to: 'messages#create'
end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/views/chatroom/index.html.erb
<h2 class="ui aligned center icon header">
  <i class="icon circular huge expand arrows alternate yellow custom-offwhite"></i>
  <span class="icon-text">OFF WHITE CHAT<span>
</h2>

<%= render 'layouts/notification' %>

<div class="container chat-layout">
  <div class="ui grid">
    <div class="twelve wide column">
      <div class="ui raised fluid card chatbox">
        <div class="content" id="chatroom-container">
          <div class="ui feed" id="message-container">
            <%= render @messages %>
          </div>
        </div>
        <div class="extra content fluid">
          <%= form_for @message, html: {class: "ui reply form", role: "form", remote: true}, url: message_path do |f| %>
            <div class="field">
              <div class="ui fluid icon input">
                <%= f.text_field :body%>
                <%= f.button ("<i class='bordered inverted orange edit icon'></i>").html_safe, id:"chatbox-button" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="four wide column">
      <div class="ui fluid raised card chatbox">
        <div class="content">
          <div class="ui inverted vertical menu">
            <a class="active item">
              Home
            </a>
            <a class="item">
              Messages
            </a>
            <a class="item">
              Friends
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>